/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorytoko;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import koneksi.koneksi;

/**
 *
 * @author OsaFirzian
 */
public class FormDashboard extends javax.swing.JFrame {
    
//        private String username; // Tambahkan field untuk menyimpan username
        private String loggedInUsername; // Untuk menyimpan username yang login
        private String loggedInRole;     // Untuk menyimpan role yang login

        //Buat Jam
    private void showTanggalDanJam() {
        // Format tanggal
        SimpleDateFormat tglFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat jamFormat = new SimpleDateFormat("HH:mm:ss");

        // Timer berjalan setiap detik
        Timer timer = new Timer(1000, (e) -> {
            Date now = new Date();
            labelTanggal.setText(tglFormat.format(now));
            labelJam.setText(jamFormat.format(now));
        });
        timer.start();
    }
    
    private void displayUserAndRole() {
        
        labelUser.setText("User: " + loggedInUsername + "   Role: " + loggedInRole); 
        // Pastikan Anda memiliki JLabel dengan nama lblUserInfo di desain FormDashboard Anda.
    } 
    
    /**
     * Creates new form TampilanUtama
     */
    public FormDashboard() {
        initComponents();
        showTanggalDanJam();
    }
    
    public FormDashboard(String username, String role) {
        initComponents();
//        this.username = username;
        showTanggalDanJam();
        
        this.loggedInUsername = username;
        this.loggedInRole = role;
        displayUserAndRole();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseBG = new javax.swing.JPanel();
        Laporan = new javax.swing.JButton();
        DataPenyewa = new javax.swing.JButton();
        BarangKeluar = new javax.swing.JButton();
        BarangMasuk = new javax.swing.JButton();
        StokBarang = new javax.swing.JButton();
        Dashboard = new javax.swing.JButton();
        labelJam = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        pn_penyewa = new javax.swing.JPanel();
        penyewa = new javax.swing.JLabel();
        IconPenyewa = new javax.swing.JLabel();
        nilaipenyewa = new javax.swing.JLabel();
        pn_barangmasuk = new javax.swing.JPanel();
        jumlahBarangMasuk = new javax.swing.JLabel();
        IconBrgMasuk = new javax.swing.JLabel();
        barangmasuk = new javax.swing.JLabel();
        pn_barangkeluar = new javax.swing.JPanel();
        jumlahBarang1 = new javax.swing.JLabel();
        IconBrgKeluar = new javax.swing.JLabel();
        JumlahBarangKeluar = new javax.swing.JLabel();
        pn_barang = new javax.swing.JPanel();
        jumlahBarang = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        JumlahBarang = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        exitbtn = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                baseBGMouseDragged(evt);
            }
        });
        baseBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baseBGMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                baseBGMousePressed(evt);
            }
        });
        baseBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Laporan.setBackground(new java.awt.Color(254, 129, 0));
        Laporan.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Laporan.setForeground(new java.awt.Color(255, 255, 255));
        Laporan.setText("Laporan");
        Laporan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Laporan.setBorderPainted(false);
        Laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Laporan.setFocusPainted(false);
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LaporanMouseExited(evt);
            }
        });
        baseBG.add(Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 380, 135, 35));

        DataPenyewa.setBackground(new java.awt.Color(254, 129, 0));
        DataPenyewa.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        DataPenyewa.setForeground(new java.awt.Color(255, 255, 255));
        DataPenyewa.setText("Data Penyewa");
        DataPenyewa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DataPenyewa.setBorderPainted(false);
        DataPenyewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPenyewa.setFocusPainted(false);
        DataPenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataPenyewaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataPenyewaMouseExited(evt);
            }
        });
        baseBG.add(DataPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 330, 135, 35));

        BarangKeluar.setBackground(new java.awt.Color(254, 129, 0));
        BarangKeluar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BarangKeluar.setText("Barang Keluar");
        BarangKeluar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BarangKeluar.setBorderPainted(false);
        BarangKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarangKeluar.setFocusPainted(false);
        BarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarangKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarangKeluarMouseExited(evt);
            }
        });
        baseBG.add(BarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 280, 135, 35));

        BarangMasuk.setBackground(new java.awt.Color(254, 129, 0));
        BarangMasuk.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        BarangMasuk.setText("Barang Masuk");
        BarangMasuk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BarangMasuk.setBorderPainted(false);
        BarangMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarangMasuk.setFocusPainted(false);
        BarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarangMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarangMasukMouseExited(evt);
            }
        });
        baseBG.add(BarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, 135, 35));

        StokBarang.setBackground(new java.awt.Color(254, 129, 0));
        StokBarang.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        StokBarang.setForeground(new java.awt.Color(255, 255, 255));
        StokBarang.setText("Stok Barang");
        StokBarang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        StokBarang.setBorderPainted(false);
        StokBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StokBarang.setFocusPainted(false);
        StokBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StokBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StokBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StokBarangMouseExited(evt);
            }
        });
        baseBG.add(StokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 135, 35));

        Dashboard.setBackground(new java.awt.Color(254, 129, 0));
        Dashboard.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Dashboard.setBorderPainted(false);
        Dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashboard.setFocusPainted(false);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
        });
        baseBG.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, 135, 35));

        labelJam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelJam.setText("HH:mm:ss");
        baseBG.add(labelJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 70, 15));

        labelTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTanggal.setText("yyyy-MM-dd");
        baseBG.add(labelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 90, 15));

        labelUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUser.setText("User");
        baseBG.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 160, 15));

        pn_penyewa.setBackground(new java.awt.Color(255, 179, 71));
        pn_penyewa.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        pn_penyewa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penyewa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        penyewa.setForeground(new java.awt.Color(255, 255, 255));
        penyewa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        penyewa.setText("Jumlah Penyewa");
        pn_penyewa.add(penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        IconPenyewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/People.png"))); // NOI18N
        pn_penyewa.add(IconPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 55, -1, -1));

        nilaipenyewa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nilaipenyewa.setForeground(new java.awt.Color(255, 255, 255));
        nilaipenyewa.setText("9999");
        pn_penyewa.add(nilaipenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, -1, -1));

        baseBG.add(pn_penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 200, 130));

        pn_barangmasuk.setBackground(new java.awt.Color(255, 179, 71));
        pn_barangmasuk.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        pn_barangmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlahBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jumlahBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahBarangMasuk.setText("Barang Masuk");
        pn_barangmasuk.add(jumlahBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        IconBrgMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/In.png"))); // NOI18N
        pn_barangmasuk.add(IconBrgMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 55, -1, -1));

        barangmasuk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        barangmasuk.setForeground(new java.awt.Color(255, 255, 255));
        barangmasuk.setText("9999");
        pn_barangmasuk.add(barangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, -1, -1));

        baseBG.add(pn_barangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 200, 130));

        pn_barangkeluar.setBackground(new java.awt.Color(255, 179, 71));
        pn_barangkeluar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        pn_barangkeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlahBarang1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jumlahBarang1.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBarang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahBarang1.setText("Barang Keluar");
        pn_barangkeluar.add(jumlahBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        IconBrgKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Out.png"))); // NOI18N
        pn_barangkeluar.add(IconBrgKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 55, -1, -1));

        JumlahBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JumlahBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        JumlahBarangKeluar.setText("9999");
        pn_barangkeluar.add(JumlahBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, -1, -1));

        baseBG.add(pn_barangkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 200, 130));

        pn_barang.setBackground(new java.awt.Color(255, 179, 71));
        pn_barang.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        pn_barang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlahBarang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jumlahBarang.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahBarang.setText("Jumlah Barang");
        pn_barang.add(jumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Inventory.png"))); // NOI18N
        pn_barang.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 55, -1, -1));

        JumlahBarang.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JumlahBarang.setForeground(new java.awt.Color(255, 255, 255));
        JumlahBarang.setText("9999");
        pn_barang.add(JumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 55, -1, -1));

        baseBG.add(pn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 130));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setText("DASHBOARD");
        baseBG.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 118, -1, -1));

        exitbtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtnMouseExited(evt);
            }
        });
        baseBG.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 90, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg2.jpg"))); // NOI18N
        baseBG.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(baseBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Button Exit
    private void exitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseClicked
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_exitbtnMouseClicked

    private void baseBGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseBGMouseClicked
        // TODO  your handling code here:
    }//GEN-LAST:event_baseBGMouseClicked

    
    //Biar Panelnya bisa di drag
    //Panel Utama
    int a, b;
    private void baseBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseBGMousePressed
        a = evt.getX();
        b = evt.getY();
    }//GEN-LAST:event_baseBGMousePressed

    private void baseBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baseBGMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - a, y - b);
    }//GEN-LAST:event_baseBGMouseDragged
    
    //Buat Efek Hover
    //Exit Button
    private void exitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseEntered
        exitbtn.setFont(new java.awt.Font("sansserif", 1, 18));
        exitbtn.setForeground(new java.awt.Color(255, 179, 71));
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit-hover.png")));
    }//GEN-LAST:event_exitbtnMouseEntered

    private void exitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseExited
        exitbtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png")));
    }//GEN-LAST:event_exitbtnMouseExited
    
    //Buat Efek Hover
    //Dashboard
    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        Dashboard.setBackground(new java.awt.Color(255, 179, 71));
        Dashboard.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        Dashboard.setBackground(new java.awt.Color(254, 129, 0));
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DashboardMouseExited

    
    //Buat Efek Hover
    //Stok Barang
    private void StokBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StokBarangMouseEntered
        StokBarang.setBackground(new java.awt.Color(255, 179, 71));
        StokBarang.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_StokBarangMouseEntered

    private void StokBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StokBarangMouseExited
        StokBarang.setBackground(new java.awt.Color(254, 129, 0));
        StokBarang.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_StokBarangMouseExited

    
    //Buat Efek Hover
    //Barang Masuk
    private void BarangMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMasukMouseEntered
        BarangMasuk.setBackground(new java.awt.Color(255, 179, 71));
        BarangMasuk.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_BarangMasukMouseEntered

    private void BarangMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMasukMouseExited
        BarangMasuk.setBackground(new java.awt.Color(254, 129, 0));
        BarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BarangMasukMouseExited
    
    
    //Buat Efek Hover
    //Barang Keluar
    private void BarangKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangKeluarMouseEntered
        BarangKeluar.setBackground(new java.awt.Color(255, 179, 71));
        BarangKeluar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_BarangKeluarMouseEntered

    private void BarangKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangKeluarMouseExited
        BarangKeluar.setBackground(new java.awt.Color(254, 129, 0));
        BarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_BarangKeluarMouseExited
    
    
    //Buat Efek Hover
    //Data Penyewa
    private void DataPenyewaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPenyewaMouseEntered
        DataPenyewa.setBackground(new java.awt.Color(255, 179, 71));
        DataPenyewa.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_DataPenyewaMouseEntered

    private void DataPenyewaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPenyewaMouseExited
        DataPenyewa.setBackground(new java.awt.Color(254, 129, 0));
        DataPenyewa.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_DataPenyewaMouseExited
    
    
    //Buat Efek Hover
    //Data Laporan
    private void LaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseEntered
        Laporan.setBackground(new java.awt.Color(255, 179, 71));
        Laporan.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_LaporanMouseEntered

    private void LaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseExited
        Laporan.setBackground(new java.awt.Color(254, 129, 0));
        Laporan.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_LaporanMouseExited

    
    //Perpindahan Antar Dashboard
    private void StokBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StokBarangMouseClicked
    FormStokbarang stokBarang = new FormStokbarang();
    stokBarang.setVisible(true); // Menampilkan form baru
    
    //Buat menyimpan nilai User dan Role agar tidak hilang saat berpindah JForm
    new FormStokbarang(this.loggedInUsername, this.loggedInRole).setVisible(true);
    
    this.dispose(); // Menutup form sekarang
    }//GEN-LAST:event_StokBarangMouseClicked

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
    FormDashboard dashboard = new FormDashboard();
    dashboard.setVisible(true);
    
    //Buat menyimpan nilai User dan Role agar tidak hilang saat berpindah JForm
    new FormDashboard(this.loggedInUsername, this.loggedInRole).setVisible(true);
    
    this.dispose();
    }//GEN-LAST:event_DashboardMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BarangKeluar;
    private javax.swing.JButton BarangMasuk;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton DataPenyewa;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel IconBrgKeluar;
    private javax.swing.JLabel IconBrgMasuk;
    private javax.swing.JLabel IconPenyewa;
    private javax.swing.JLabel JumlahBarang;
    private javax.swing.JLabel JumlahBarangKeluar;
    private javax.swing.JButton Laporan;
    private javax.swing.JButton StokBarang;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel background;
    private javax.swing.JLabel barangmasuk;
    private javax.swing.JPanel baseBG;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel jumlahBarang;
    private javax.swing.JLabel jumlahBarang1;
    private javax.swing.JLabel jumlahBarangMasuk;
    private javax.swing.JLabel labelJam;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel nilaipenyewa;
    private javax.swing.JLabel penyewa;
    private javax.swing.JPanel pn_barang;
    private javax.swing.JPanel pn_barangkeluar;
    private javax.swing.JPanel pn_barangmasuk;
    private javax.swing.JPanel pn_penyewa;
    // End of variables declaration//GEN-END:variables
}
