/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorytoko;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Set;
import koneksi.koneksi;

/**
 *
 * @author OsaFirzian
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        
        PasswordUser.setText("     Password");
        PasswordUser.setEchoChar((char)0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TeksUser = new javax.swing.JTextField();
        PasswordUser = new javax.swing.JPasswordField();
        ButtonLogin = new javax.swing.JButton();
        BackgroundPanel = new javax.swing.JPanel();
        BackgroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(255, 255, 255)));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        PanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        TeksUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TeksUser.setForeground(new java.awt.Color(204, 204, 204));
        TeksUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TeksUser.setText("     Username");
        TeksUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TeksUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TeksUserFocusLost(evt);
            }
        });
        PanelLogin.add(TeksUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, 35));

        PasswordUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordUser.setForeground(new java.awt.Color(204, 204, 204));
        PasswordUser.setText("     Password");
        PasswordUser.setEchoChar(' ');
        PasswordUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordUserFocusLost(evt);
            }
        });
        PanelLogin.add(PasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 300, 35));

        ButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonLogin.setText("Login");
        ButtonLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLoginMouseClicked(evt);
            }
        });
        PanelLogin.add(ButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, 30));

        getContentPane().add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 95, 400, 400));

        BackgroundPanel.setBackground(new java.awt.Color(248, 248, 248));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BGLogin.jpg"))); // NOI18N
        BackgroundPanel.add(BackgroundIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
            
    private void PasswordUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordUserFocusGained
        if (String.valueOf(PasswordUser.getPassword()).equals("     Password")) {
            PasswordUser.setText("");
            PasswordUser.setEchoChar('*'); // Tampilkan bintang saat mulai mengetik
            PasswordUser.setForeground(new java.awt.Color(204, 204, 204));
            PasswordUser.setFont(new java.awt.Font("Segoe UI", 0, 16));
        }
    }//GEN-LAST:event_PasswordUserFocusGained

    private void PasswordUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordUserFocusLost
        if (PasswordUser.getPassword().length == 0) {
            PasswordUser.setEchoChar((char) 0); // Hapus bintang
            PasswordUser.setText("     Password");
            PasswordUser.setForeground(new java.awt.Color(204, 204, 204));
            PasswordUser.setFont(new java.awt.Font("Segoe UI", 0, 16));
        }
    }//GEN-LAST:event_PasswordUserFocusLost

    private void TeksUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TeksUserFocusGained
        if (String.valueOf(TeksUser.getText()).equals("     Username")) {
            TeksUser.setText("");
            TeksUser.setForeground(new java.awt.Color(204, 204, 204));
            TeksUser.setFont(new java.awt.Font("Segoe UI", 0, 16));
        }
    }//GEN-LAST:event_TeksUserFocusGained

    private void TeksUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TeksUserFocusLost
        if (TeksUser.getText().isEmpty()){
            TeksUser.setText("     Username");
            TeksUser.setForeground(new java.awt.Color(204, 204, 204));
            TeksUser.setFont(new java.awt.Font("Segoe UI", 0, 16));
        }
    }//GEN-LAST:event_TeksUserFocusLost

    private void ButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLoginMouseClicked
        String username = TeksUser.getText();
        String password = String.valueOf(PasswordUser.getPassword());

        try {
        koneksi con = new koneksi(); // objek dari class koneksi
        Connection conn = con.connect();

        String sql = "SELECT * FROM inventorytoko.user WHERE Nama = ? AND Password = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, password);

        ResultSet rs = pst.executeQuery();

//        if (rs.next()) {JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + role);
//            String role = rs.getString("role");
//            JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + role);
//
//            this.setVisible(false); // sembunyikan login form
//
//            if (role.equals("admin")) {
//                new FormDashboard(username).setVisible(true);
//            } else if (role.equals("user")) {
//                new FormStokbarang(username).setVisible(true);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Username atau password salah!");
//        }
        
        if (rs.next()) {
            String role = rs.getString("role");
            JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + role);
            this.setVisible(false); // sembunyikan login form

            if (role.equals("Admin")) {
                new FormDashboard(username).setVisible(true);
            } else if (role.equals("Staff")) {
                new FormStokbarang(username).setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Username atau password salah!");
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal login: " + e.getMessage());
    }
    }//GEN-LAST:event_ButtonLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundIcon;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPasswordField PasswordUser;
    private javax.swing.JTextField TeksUser;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
